### ISSUE TITLE
Question: I ordered the OpenScan Classic 'kit' minus the 3d prints...where do I mount the electronics / camera, etc in your version?

### ISSUE THREAD

**Issue by MrMxyzptlk** [pat149/OpenScan_Classic_Premium#3]
Question: I ordered the OpenScan Classic 'kit' minus the 3d prints...where do I mount the electronics / camera, etc in your version?

Thanks for your work!

**Comment by pat149** [comment]
Hey,

the Raspberry stand has to be used from the original version. The camera stand you have to purchase or print by yourself, depending on which camera you want to use. I might think about updating the design so that the Raspberry can be mounted directly onto the stand. But the last year was really busy and probably the coming year will be too.

**Comment by MrMxyzptlk** [comment]
Thank you! I'm using the autofocus Arducam IMX519

**Comment by MrMxyzptlk** [comment]
Does this look like the right part to print for the rPi, Arducam, and network?

Pi Shield_RPi_with_Ringlight_and_Network+USB.stl
 
This is from the official openscan classic github

**Comment by pat149** [comment]
That‘s one part of it, yes. There‘s another repository where you can download the rest of the scanner. I‘ll put the link below.
You‘ll need the correct Pi-Shield-stl and the Turntable-Adapter. Everything else should be provided with my new design.

https://github.com/OpenScan-org/OpenScan-Design/tree/main/STL/Classic/V1

**Comment by MrMxyzptlk** [comment]
Thanks.
